"Category: Admin":
  # Source
  - bluebot/cogs/admin/*
  # Docs
  - docs/cog_guides/admin.rst
"Category: Alias":
  # Source
  - bluebot/cogs/alias/*
  # Docs
  - docs/cog_guides/alias.rst
"Category: Audio Cog":
  - any:
      - bluebot/cogs/audio/**/*
    all:
      - "!bluebot/cogs/audio/**/locales/*"
"Category: Bank API":
  # Source
  - bluebot/core/bank.py
  # Docs
  - docs/framework_bank.rst
"Category: Bot Core":
  # Source
  - bluebot/*
  - bluebot/core/__init__.py
  - bluebot/core/_diagnoser.py
  - bluebot/core/_sharedlibdeprecation.py
  - bluebot/core/bot.py
  - bluebot/core/checks.py
  - bluebot/core/cli.py
  - bluebot/core/cog_manager.py
  - bluebot/core/core_commands.py
  - bluebot/core/data_manager.py
  - bluebot/core/errors.py
  - bluebot/core/events.py
  - bluebot/core/global_checks.py
  - bluebot/core/settings_caches.py
  # Docs
  - docs/framework_apikeys.rst
  - docs/framework_bot.rst
  - docs/framework_cogmanager.rst
  - docs/framework_datamanager.rst
  - docs/framework_events.rst
  - docs/cog_guides/cog_manager_ui.rst
  - docs/cog_guides/core.rst
"Category: CI":
  - .github/workflows/*
"Category: Cleanup Cog":
  # Source
  - bluebot/cogs/cleanup/*
  # Docs
  - docs/cog_guides/cleanup.rst
"Category: Command Module":
  # Source
  - any:
      # Source
      - bluebot/core/commands/*
      # Docs
      - docs/framework_checks.rst
      - docs/framework_commands.rst
    all:
      - "!bluebot/core/commands/help.py"
"Category: Config":
  # Source
  - bluebot/core/drivers/*
  - bluebot/core/config.py
  # Docs
  - docs/framework_config.rst
"Category: CustomCom":
  # Source
  - bluebot/cogs/customcom/*
  # Docs
  - docs/cog_customcom.rst
  - docs/cog_guides/customcommands.rst
"Category: Dev Cog":
  - bluebot/core/dev_commands.py
"Category: Docs":
  - docs/**/*
"Category: Downloader":
  # Source
  - bluebot/cogs/downloader/*
  # Docs
  - docs/cog_guides/downloader.rst
"Category: Economy Cog":
  # Source
  - bluebot/cogs/economy/*
  # Docs
  - docs/cog_guides/economy.rst
"Category: Filter":
  # Source
  - bluebot/cogs/filter/*
  # Docs
  - docs/cog_guides/filter.rst
"Category: General Cog":
  # Source
  - bluebot/cogs/general/*
  # Docs
  - docs/cog_guides/general.rst
"Category: Help":
  - bluebot/core/commands/help.py
"Category: i18n":
  # Source
  - bluebot/core/i18n.py
  # Locale files
  - bluebot/**/locales/*
  # Docs
  - docs/framework_i18n.rst
"Category: Image":
  # Source
  - bluebot/cogs/image/*
  # Docs
  - docs/cog_guides/image.rst
"Category: Meta":
  - ./*
  - .github/*
  - .github/ISSUE_TEMPLATE/*
  - .github/PULL_REQUEST_TEMPLATE/*
  - schema/*
  - tools/*
"Category: Mod Cog":
  # Source
  - bluebot/cogs/mod/*
  # Docs
  - docs/cog_guides/mod.rst
"Category: Modlog API":
  # Source
  - bluebot/core/generic_casetypes.py
  - bluebot/core/modlog.py
  # Docs
  - docs/framework_modlog.rst
"Category: Modlog Cog":
  # Source
  - bluebot/cogs/modlog/*
  # Docs
  - docs/cog_guides/modlog.rst
"Category: Mutes Cog":
  # Source
  - bluebot/cogs/mutes/*
  # Docs
  - docs/cog_guides/mutes.rst
"Category: Permissions":
  # Source
  - bluebot/cogs/permissions/*
  # Docs
  - docs/cog_guides/permissions.rst
  - docs/cog_permissions.rst
"Category: Reports Cog":
  # Source
  - bluebot/cogs/reports/*
  # Docs
  - docs/cog_guides/reports.rst
"Category: RPC/ZMQ API":
  # Source
  - bluebot/core/rpc.py
  # Docs
  - docs/framework_rpc.rst
"Category: Streams":
  # Source
  - bluebot/cogs/streams/*
  # Docs
  - docs/cog_guides/streams.rst
"Category: Tests":
  - bluebot/pytest/*
  - tests/**/*
"Category: Trivia Cog":
  # Source
  - bluebot/cogs/trivia/*
  # Docs
  - docs/cog_guides/trivia.rst
  - docs/guide_trivia_list_creation.rst
"Category: Trivia Lists":
  - bluebot/cogs/trivia/data/lists/*
"Category: Utility Functions":
  # Source
  - bluebot/core/utils/*
  # Docs
  - docs/framework_utils.rst
"Category: Warnings":
  # Source
  - bluebot/cogs/warnings/*
  # Docs
  - docs/cog_guides/warnings.rst
