version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  commands:
    - pip install .[doc]
    - cat docs/conf.py
    - python -m sphinx -T -b html -d _build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
