dist: trusty
language: python
python:
  - "3.5.3"
  - "3.6.1"
install:
  - echo "pytest>3" >> requirements.txt
  - echo "pytest-asyncio" >> requirements.txt
  - echo "git+https://github.com/Rapptz/discord.py.git@rewrite#egg=discord.py[voice]" >> requirements.txt
  - pip install -r requirements.txt
  - pip install -e .
script:
  - python -m compileall ./redbot/cogs
  - python -m pytest
before_deploy:
  - curl https://artifacts.crowdin.com/repo/GPG-KEY-crowdin | sudo apt-key add -
  - echo "deb https://artifacts.crowdin.com/repo/deb/ /" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y crowdin
deploy:
  provider: script
  script: python3 ./generate_strings.py
  on:
    branch: V3/develop
    python: 3.5.3
cache: pip
notifications:
  email: false