version: "3"

services:
  redbot: 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./docker/data:/home/red/.local/share/Red-DiscordBot"
    restart: always
    env_file:
      - ./docker/.env
    command: python3.6 -m redbot docker --no-prompt --dev --mentionable --prefix ${PREFIX}