version: "3"

services:
  mongo:
    image: mongo
    restart: always
    command: "--smallfiles --logpath=/dev/null"
    volumes:
      - ./data/db:/data/db
    # Uncomment for local mongo access. WARNING: NO AUTHENTICATION
    #ports:
    #  - "27017:27017"

  lavalink:
    # Comment image and uncomment ../lavalink to build using .jar
    image: fredboat/lavalink:master-v3
    #build: ../lavalink
    restart: always
    volumes:
      - ../lavalink/application.yml:/opt/Lavalink/application.yml:ro
    expose:
     - "2332"
     - "2333"

  red:
    build:
      context: ../..
      dockerfile: docker/red-mongodb/Dockerfile
    restart: on-failure
    command: "--token ${BOT_TOKEN} --prefix ${BOT_PREFIX}"
    environment:
      - LAVALINK_DEFAULT_HOST=lavalink=
    volumes:
      - ./data/red:/data
    links:
      - mongo
      - lavalink
