name: Lint Python
on:
  pull_request:
  push:
  repository_dispatch:
    types:
      - dispatched_test

env:
  ref: ${{ github.event.client_payload.ref || '' }}

jobs:
  lint_python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: "python -m pip install ruff"
        name: Install Ruff
      - run: "python -m ruff . --format=github --show-source"
        name: Run Ruff
