name: Build packages

on:
  push:
  pull_request:

jobs:
  debian:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.ref }}
      - name: Create output directory
        run: mkdir artifacts
      - name: Install dependencies
        run: |
          apt update
          apt -y install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev \
                libsqlite3-dev wget curl llvm libncurses5-dev xz-utils tk-dev libxml2-dev \
                libxmlsec1-dev libffi-dev liblzma-dev libgdbm-dev uuid-dev python3-openssl git \
                openjdk-11-jre-headless debhelper devscripts equivs python3-all \
                python3-setuptools python3-pip dh-python dh-virtualenv
          CXX=/usr/bin/g++
      - name: Install Python
        shell: bash -leo pipefail {0}
        run: |
          command -v pyenv && pyenv update || curl https://pyenv.run | bash
          echo 'export PATH="'$HOME'/.pyenv/bin:$PATH"' >> ~/.profile
          echo 'eval "$(pyenv init -)"' >> ~/.profile
          echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.profile
          source ~/.profile
          CONFIGURE_OPTS=--enable-optimizations pyenv install 3.8.5 -v
          pyenv global 3.8.5
      - name: Build Debian package
        run: dpkg-buildpackage -us -uc -b
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Debian packaging output
          path: artifacts/
