name: Build packages

on:
  push:
  pull_request:

jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.ref }}
      - name: Create output directory
        run: mkdir artifacts
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential debhelper devscripts equivs python3-all \
            python3-setuptools python3.8-dev python3-pip dh-python git openjdk-11-jre-headless \
            python3-virtualenv python3-sphinx-rtd-theme python3-sphinx aptitude
      - name: Check dependencies
        run: |
          aptitude python3-sphinx-rtd-theme
          apt-cache policy python3-sphinx-rtd-theme
      - name: Install dh-virtualenv
        shell: bash -leo pipefail {0}
        run: |
          docker build --tag dh-venv-builder https://github.com/spotify/dh-virtualenv.git#1.2.1 --build-arg distro=ubuntu:focal
          mkdir -p dist && docker run --rm dh-venv-builder tar -C /dpkg -c . | tar -C dist -xv
          sudo dpkg -i dist/dh-virtualenv*.deb
      - name: Build Debian package
        run: dpkg-buildpackage -us -uc -b
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Debian packaging output
          path: artifacts/
