name: Build packages

on:
  push:
  pull_request:

jobs:
  debian:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.ref }}
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install build-essential debhelper devscripts equivs python3-all \
            python3-setuptools python3.8-dev python3-pip dh-python git openjdk-11-jre-headless \
            python3-virtualenv python3-sphinx-rtd-theme python3-sphinx dh-virtualenv
      - name: Build Debian package
        run: dpkg-buildpackage -us -uc -b
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Debian packaging output
          path: |
            ./red-discordbot*.deb
            ./red-discordbot*.ddeb
            ./red-discordbot*.buildinfo
            ./red-discordbot*.changes
