name: Build packages

on:
  push:
  pull_request:

jobs:
  debian:
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.ref }}
      - name: Create output directory
        run: mkdir artifacts
      - name: Install dependencies
        run: |
          sudo apt-get install build-essential debhelper devscripts equivs python3-all \
            python3-setuptools python3.8-dev python3-pip dh-python git openjdk-11-jre-headless dh-virtualenv
      - name: Build Debian package
        run: dpkg-buildpackage -us -uc -b
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Debian packaging output
          path: artifacts/
