name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Cache
      uses: actions/cache@v1.0.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/tox.ini') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Tox test - Py
      env:
        TOXENV: py
      run: tox
    - name: Tox test - Style
      env:
        TOXENV: style
      run: tox
    - name: Tox test - Docs
      env:
        TOXENV: docs
      run: tox
